name: Compile Assets (Vite)
on: [push, pull_request]
jobs:
  build-assets:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
    name: ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v1
      - name: Install NPM Dependencies
        run: npm install
      - name: Compile Assets (Vite)
        run: npm run build